//
//  ListMoviesPresenter.swift
//  Antares
//
//  Created by Leandro Romano on 05/05/19.
//  Copyright (c) 2019 Leandro Romano. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListMoviesPresentationLogic {
    func presentMovies(response: ListMovies.Response)
    func presentError(_ error: Error)
}

class ListMoviesPresenter: ListMoviesPresentationLogic {

    weak var viewController: ListMoviesDisplayLogic?
    
    func presentMovies(response: ListMovies.Response) {
        let viewModel = ListMovies.ViewModel(page: response.page, movies: response.results.map { return MovieViewModel(movie: $0) })
        viewController?.displayMovies(viewModel: viewModel)
    }
    
    func presentError(_ error: Error) {
        viewController?.displayError(error)
    }
    
}
