//
//  ListMoviesInteractor.swift
//  Antares
//
//  Created by Leandro Romano on 05/05/19.
//  Copyright (c) 2019 Leandro Romano. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListMoviesBusinessLogic {
    var numberOfItems: Int { get }
    func getMovies(by category: MovieCategory)
    func cellForItem(at index: Int) -> ListMovies.ViewModel
    func didSelectRow(at index: Int)
}

protocol ListMoviesDataStore {
    var movieId: Int? { get }
}

class ListMoviesInteractor: ListMoviesBusinessLogic, ListMoviesDataStore {

    var presenter: ListMoviesPresentationLogic?
    var worker: ListMoviesWorker?
    
    var movies = [Movie]()
    var movieId: Int?
    var numberOfItems: Int {
        return movies.count
    }
    
    init(worker: ListMoviesWorker = ListMoviesWorker()) {
        self.worker = worker
    }
    
    func getMovies(by category: MovieCategory) {
        worker?.retrieveMovies(for: category).done(handleSuccess).catch(handleError)
    }
    
    private func handleSuccess(_ response: ListMovies.Response) {
        movies = response.results
        presenter?.presentDynamicData()
    }
    
    private func handleError(_ error: Error) {
        presenter?.presentError(error)
    }
    
    func cellForItem(at index: Int) -> ListMovies.ViewModel {
        return ListMovies.ViewModel(movie: movies[index])
    }
    
    func didSelectRow(at index: Int) {
        movieId = movies[index].id
        presenter?.presentMovieDetails()
    }
    
}
