//
//  ListMoviesWorker.swift
//  Antares
//
//  Created by Leandro Romano on 05/05/19.
//  Copyright (c) 2019 Leandro Romano. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import PromiseKit

class ListMoviesWorker {
    
    let networkProvider = NetworkProvider.shared
    
    func retrieveMovies(for category: MovieCategory) -> Promise<ListMovies.Response> {
        return networkProvider.request(.search(by: category))
    }

}
