//
//  ListMoviesRouter.swift
//  Antares
//
//  Created by Leandro Romano on 05/05/19.
//  Copyright (c) 2019 Leandro Romano. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListMoviesRoutingLogic {
    func routeToDetails()
}

protocol ListMoviesDataPassing {
    var dataStore: ListMoviesDataStore? { get }
}

class ListMoviesRouter: NSObject, ListMoviesRoutingLogic, ListMoviesDataPassing {

    weak var viewController: ListMoviesViewController?
    var dataStore: ListMoviesDataStore?

    func routeToDetails() {
        let vc = MovieDetailsViewController()
        guard
            let dataStore = dataStore,
            let destinationRouter = vc.router,
            var destinationDataStore = destinationRouter.dataStore
        else { return }
        passDataToDetails(source: dataStore, destination: &destinationDataStore)
        viewController?.present(vc, animated: true)
    }
    
    private func passDataToDetails(source: ListMoviesDataStore, destination: inout MovieDetailsDataStore) {
        destination.movieId = source.movieId
    }

}
