//
//  MovieDetailsWorker.swift
//  Antares
//
//  Created by Leandro Romano on 24/08/19.
//  Copyright (c) 2019 Leandro Romano. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import PromiseKit

class MovieDetailsWorker {

    let networkProvider = NetworkProvider.shared
    
    func retrieveDetailsForMovie(id movieId: Int) -> Promise<MovieDetails.Response> {
        return networkProvider.request(.getDetailsForMovie(id: movieId))
    }

}
